<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="src/Edi.Core/Edi.Core.csproj" />
    <ProjectReference Include="src/Edi.Edifact/Edi.Edifact.csproj" />
    <ProjectReference Include="src/Edi.X12/Edi.X12.csproj" />
    <ProjectReference Include="src/Edi.Dictionaries/Edi.Dictionaries.csproj" />
  </ItemGroup>
</Project>
