<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Edi.Edifact</RootNamespace>
    <AssemblyName>Edi.Edifact</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Edi.Core\Edi.Core.csproj" />
  </ItemGroup>
</Project>
