<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Edi.Dictionaries</RootNamespace>
    <AssemblyName>Edi.Dictionaries</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Edi.Core\Edi.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Data\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
</Project>
